//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int idPerson { get; set; }
        public string Name { get; set; }
        public Nullable<int> invnum { get; set; }
        public string invtype { get; set; }
        public Nullable<double> price { get; set; }
        public string adress { get; set; }
    }
}
